name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  opt:  
    description: 'start or stop dotnet scan'
    required: true
    default: 'start' 
    
outputs:
  sonarqube-report:
    description: "SonarQube Report"
    value: "Report"
runs:
  using: 'node12'
  main: 'dist/index.js'